### ISSUE TITLE
Shader Editor button doesn't always open Shader Editor

### ISSUE THREAD

**Issue by melak47** [RxLaboratory/DuBLF_DuViews#1]
For me, it sometimes opens an Animation Nodes Editor instead (a node view from an addon), and sometimes a Compositor view.

If I disable the animation node addon, it works -- not sure if this is their fault or not.
But it can be worked around by doing something like
```py
if area.type == 'NODE_EDITOR':
    area.ui_type = 'ShaderNodeTree'
```
to always open a Shader Editor.

**Comment by Nico-Duduf** [comment]
I didn't have animation node installed when I tested.
Thanks for the feedback, I'll fix this!

**Comment by Nico-Duduf** [comment]
fixed,
DuViews now detects if Animation Nodes is enabled, and in this case shows an entry for it too ;)
