### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mamoun86** [RxLaboratory/DuBLF_DuViews#2]
![image](https://user-images.githubusercontent.com/40662938/67260783-ee853800-f4a5-11e9-9bec-2617f27b4b31.png)

How to fix this?

blender v : blender 2.82 (alpha)
OS : windows 10 Pro

thanks

**Comment by Nico-Duduf** [comment]
I think something changes in the python API in blender 2.82alpha and broke the little hack I use for opening new windows.

Can you try on 2.8?

**Comment by mamoun86** [comment]
Ah sorry
worked
Thanks
